name: Deploy Backstage To Test

on: push

permissions:
  contents: write # Needed for release step
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Prod Release
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Tag PROD release
        uses: rymndhng/release-on-push-action@8e3c8b4b322c06d1032728971a4eb076e45cd33e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          release_body: |
            ENV: Prod
            SHA: ${{ github.sha }}
            **PATH**: ${{ github.WORKFLOW_REF }}

            
